/*****************************************************************************
 * Source code information
 * -----------------------
 * Original author    Andreas Langegger, Johannes Kepler University Linz, Austria
 * Author email       al@jku.at
 * Package            @package@
 * Web site           @website@
 * Created            14 Jan 2010 11:32
 * @copyright@
 *****************************************************************************/

// Package
///////////////////////////////////////
package at.jku.rdfstats.vocabulary;

// Imports
///////////////////////////////////////
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;


/**
 * Vocabulary definitions from file:vocabulary/purl.org/rdfstats/stats.n3
 * @author Auto-generated by schemagen on 14 Jan 2010 11:32
 */
public class Stats {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.RDFS_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/rdfstats/stats#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    



    /* Vocabulary properties */

    public static final OntProperty classDimension = m_model.createOntProperty( "http://purl.org/rdfstats/stats#classDimension" );
    
    public static final OntProperty propertyDimension = m_model.createOntProperty( "http://purl.org/rdfstats/stats#propertyDimension" );
    
    public static final OntProperty rangeDimension = m_model.createOntProperty( "http://purl.org/rdfstats/stats#rangeDimension" );
    
    public static final OntProperty sourceType = m_model.createOntProperty( "http://purl.org/rdfstats/stats#sourceType" );
    
    public static final OntProperty sourceUrl = m_model.createOntProperty( "http://purl.org/rdfstats/stats#sourceUrl" );
    

    /* Vocabulary classes */

    public static final OntClass Histogram = m_model.createClass( "http://purl.org/rdfstats/stats#Histogram" );
    
    public static final OntClass PropertyHistogram = m_model.createClass( "http://purl.org/rdfstats/stats#PropertyHistogram" );
    
    public static final OntClass RDFDocument = m_model.createClass( "http://purl.org/rdfstats/stats#RDFDocument" );
    
    public static final OntClass RDFStatsDataset = m_model.createClass( "http://purl.org/rdfstats/stats#RDFStatsDataset" );
    
    public static final OntClass SPARQLEndpoint = m_model.createClass( "http://purl.org/rdfstats/stats#SPARQLEndpoint" );
    
    public static final OntClass SourceType = m_model.createClass( "http://purl.org/rdfstats/stats#SourceType" );
    
    public static final OntClass SubjectHistogram = m_model.createClass( "http://purl.org/rdfstats/stats#SubjectHistogram" );
    
    public static final OntClass blankNode = m_model.createClass( "http://purl.org/rdfstats/stats#blankNode" );
    

    /* Vocabulary individuals */

}

/*
@footer@
*/

